---
apiVersion: v2
name: xnat
description: A Helm chart for deploying XNAT on Kubernetes
type: application
version: 0.0.7
# XNAT version deployed in the chart
appVersion: 1.8.10

dependencies:
  - name: postgresql
    version: 16.4.14
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
