---
apiVersion: v2
name: xnat
description: A Helm chart for deploying XNAT on Kubernetes
type: application
version: 0.0.10
# XNAT version deployed in the chart
appVersion: 1.8.10

dependencies:
  - name: cluster
    alias: postgresql
    version: 0.2.1
    repository: https://cloudnative-pg.github.io/charts
    condition: postgresql.enabled
