---
repos:
  - repo: https://github.com/bitnami/readme-generator-for-helm
    rev: 2.6.1
    hooks:
      - id: helm-readme-generator
        # in order to run helm-readme-generator only once
        pass_filenames: false
        always_run: true
        args:
          - --readme=./README.md
          - --values=charts/xnat/values.yaml
