---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-postgres
data:
  wait-for-postgres.sh: |
    #!/bin/sh
    # wait-for-postgres.sh

    set -e

    cmd="$@"

    PGPASSWORD={{ .Values.postgresql.auth.database }} until psql -U {{ .Values.postgresql.auth.username }} -h {{ template "xnat.postgresql.svc" . }}  -c '\q'; do
    >&2 echo "Postgres is unavailable - sleeping"
    sleep 5
    done

    >&2 echo "Postgres is up - executing command \"$cmd\""
    exec $cmd
