---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-postgres
data:
  wait-for-postgres.sh: |
    #!/bin/sh
    # wait-for-postgres.sh

    set -e

    until PGPASSWORD={{ .Values.postgresql.auth.database }} psql -U {{ .Values.postgresql.auth.username }} -h {{ template "xnat.postgresql.svc" . }} -c '\q'; do
    >&2 echo "Postgres is unavailable - sleeping"
    sleep 20
    done

    >&2 echo "Postgres is up"

