{{ if .Values.config.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-configure
  {{- with .Values.config.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-configure
      {{- with .Values.config.jobAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      restartPolicy: Never
      imagePullSecrets:
      {{- if .Values.imageCredentials.enabled }}
      - name: image-pull-secret
      {{- else }}
      - name: {{ .Values.image.pullSecret | quote }}
      {{- end }}
      containers:
      - name: post-install-job
        image: "{{ .Values.config.image.registry }}/{{ .Values.config.image.namespace }}/{{ .Values.config.image.name }}:{{ .Values.config.image.tag }}"
        env:
        - name: XNAT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.localdb.secretName }}
              key: adminPassword
        - name: XNAT_SERVICE_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.auth.localdb.secretName }}
              key: serviceAdminPassword
        command: ["ansible-playbook"]
        args:
          - configure-xnat.yaml
          - --extra-vars
          - xnat_url=http://{{ include "xnat.fullname" . }}
          - --extra-vars
          - xnat_admin_password="$(XNAT_ADMIN_PASSWORD)"
          - --extra-vars
          - xnat_service_admin_password="$(XNAT_SERVICE_ADMIN_PASSWORD)"
          {{- if .Values.auth.openid.enabled }}
          - --extra-vars
          - '{"xnat_enabled_providers": ["localdb", {{ .Values.auth.openid.provider | quote }}]}'
          {{- end }}
          {{- if .Values.config.extraWait }}
          - --extra-vars
          - xnat_wait_for_tomcat={{ .Values.config.extraWait }}
          {{- end }}
          - -v
{{- end }}
