apiVersion: v1
kind: Secret
metadata:
  name: openid-conf
  labels: {{- include "xnat.labels" . | nindent 4 }}
type: Opaque
stringData:
  openid-conf.properties: |
    name="UCL SSO"
    provider.id=openid1
    auth.method=OpenID
    auto.enabled=false
    auto.verified=false
    siteUrl={{ .Values.web.siteUrl }}
    openid.openid1.clientId={{ .Values.web.auth.openid.clientId }}
    openid.openid1.clientSecret={{ .Values.web.auth.openid.clientSecret }}
    openid.openid1.accessTokenUri={{ .Values.web.auth.openid.accessTokenUri }}
    openid.openid1.userAuthUri={{ .Values.web.auth.openid.userAuthUri }}
    openid.openid1.link=<a href="/openid-login?providerId=openid1">{{ .Values.web.auth.openid.link }}</a>
    openid.openid1.forceUserCreate=true
    openid.openid1.emailProperty=email
    openid.openid1.givenNameProperty=name
    openid.openid1.familyNameProperty=deliberately_unknown_property
{{ if .Values.imageCredentials.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
