apiVersion: v1
kind: Secret
metadata:
  name: xnat-conf
  labels: {{- include "xnat.labels" . | nindent 4 }}
type: Opaque
stringData:
  xnat-conf.properties: |
    #
    # xnat-conf.properties
    # XNAT http://www.xnat.org
    # Copyright (c) 2016, Washington University School of Medicine
    # All Rights Reserved
    #
    # Released under the Simplified BSD.
    #
    datasource.driver=org.postgresql.Driver
    datasource.url=jdbc:postgresql://{{ template "xnat.postgresql.svc" . }}/{{ .Values.postgresql.auth.database }}
    datasource.username={{ .Values.postgresql.auth.username }}
    datasource.password={{ .Values.postgresql.auth.password }}
    hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true
---
apiVersion: v1
kind: Secret
metadata:
  name: openid-conf
  labels: {{- include "xnat.labels" . | nindent 4 }}
type: Opaque
stringData:
  openid-conf.properties: |
    name="UCL SSO"
    provider.id=openid1
    auth.method=OpenID
    auto.enabled=false
    auto.verified=false
    siteUrl={{ .Values.web.siteUrl }}
    openid.openid1.clientId={{ .Values.web.auth.openid.clientId }}
    openid.openid1.clientSecret={{ .Values.web.auth.openid.clientSecret }}
    openid.openid1.accessTokenUri={{ .Values.web.auth.openid.accessTokenUri }}
    openid.openid1.userAuthUri={{ .Values.web.auth.openid.userAuthUri }}
    openid.openid1.link=<a href="/openid-login?providerId=openid1">UCL Single Sign On</a>
    openid.openid1.forceUserCreate=true
    openid.openid1.emailProperty=email
    openid.openid1.givenNameProperty=name
    openid.openid1.familyNameProperty=deliberately_unknown_property
