apiVersion: v1
kind: Secret
metadata:
  name: xnat-conf
  labels: {{- include "xnat.labels" . | nindent 4 }}
type: Opaque
stringData:
  xnat-conf.properties: |
    #
    # xnat-conf.properties
    # XNAT http://www.xnat.org
    # Copyright (c) 2016, Washington University School of Medicine
    # All Rights Reserved
    #
    # Released under the Simplified BSD.
    #
    datasource.driver=org.postgresql.Driver
    datasource.url=jdbc:postgresql://{{ template "xnat.postgresql.svc" . }}/{{ .Values.postgresql.auth.database }}
    datasource.username={{ .Values.postgresql.auth.username }}
    datasource.password={{ .Values.postgresql.auth.password }}
    hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true
