
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xnat.fullname" . }}
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "xnat.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xnat.fullname" . }}-headless
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "xnat.selectorLabels" . | nindent 4 }}
  sessionAffinity: "ClientIP"
