---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "xnat.fullname" . }}-web
  labels:
    {{- include "xnat.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "xnat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "xnat.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
      {{- if .Values.imageCredentials.enabled }}
        - name: image-pull-secret
      {{- else }}
        - name: {{ .Values.image.pullSecret | quote }}
      {{- end }}
      serviceAccountName: {{ include "xnat.serviceAccountName" . }}
      containers:
        - name: {{ .Release.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "xnat.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.tomcat.catalinaOpts }}
          env:
            - name: CATALINA_OPTS
              value: {{ .Values.tomcat.catalinaOpts | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          volumeMounts:
            - name: node-conf
              mountPath: /data/xnat/home/config/node-conf.properties
              subPath: node-conf.properties
            - name: xnat-conf
              mountPath: /data/xnat/home/config/xnat-conf.properties
              subPath: xnat-conf.properties
          {{- if .Values.auth.openid.enabled }}
            - name: openid-conf
              mountPath: /data/xnat/home/config/auth/{{ .Values.auth.openid.provider }}-provider.properties
              readOnly: true
              subPath: {{ .Values.auth.openid.provider }}-provider.properties
          {{- end }}
          {{- range $vol := (concat .Values.volumeMounts .Values.extraVolumeMounts) }}
            - name: {{ $vol.name }}
              mountPath: {{ $vol.mountPath }}
              subPath: {{ $vol.subPath }}
          {{- end }}
          command:
            - /bin/bash
            - -c
            - |
              /usr/local/tomcat/bin/catalina.sh run
        {{- if .Values.logging.enabled }}
        - name: {{ .Release.Name }}-log-reader # Sidecar container
          image: grafana/alloy:latest
          command:
            - /bin/bash
            - -c
            - /bin/alloy run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy/config.alloy
              subPath: config.alloy
            {{- range $vol := .Values.volumeMounts }}
            {{- if or (eq $vol.name "xnat-home-logs") (eq $vol.name "catalina-logs") }}
            - name: {{ $vol.name }}
              mountPath: {{ $vol.mountPath }}
              subPath: {{ $vol.subPath }}
            {{- end }}
            {{- end }}
        {{- end }}
      initContainers:
        - name: wait-for-postgres
          image: {{ include "xnat.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.cluster.initdb.secret.name }}
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.cluster.initdb.secret.name }}
                  key: password
            - name: PGDATABASE
              value: {{ .Values.postgresql.cluster.initdb.database }}
          command:
            - /bin/bash
            - -c
            - |
              set -e
              until psql -h {{ template "xnat.postgresql.svc" . }} -c '\q'; do
                >&2 echo "Postgres is unavailable - sleeping"
                sleep 30
              done
              >&2 echo "Postgres is up"
        - name: xnat-datasource
          image: {{ include "xnat.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: XNAT_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.cluster.initdb.secret.name }}
                  key: username
            - name: XNAT_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.cluster.initdb.secret.name }}
                  key: password
          command:
            - /bin/bash
            - -c
            - |
              set -x
              cat <<EOF > /xnat/xnat-conf.properties
              datasource.driver=org.postgresql.Driver
              datasource.url=jdbc:postgresql://{{ template "xnat.postgresql.svc" . }}/{{ .Values.postgresql.cluster.initdb.database }}
              datasource.username=$(XNAT_DATASOURCE_USERNAME)
              datasource.password=$(XNAT_DATASOURCE_PASSWORD)
              hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
              hibernate.hbm2ddl.auto=update
              hibernate.show_sql=false
              hibernate.cache.use_second_level_cache=true
              hibernate.cache.use_query_cache=true
              EOF
          volumeMounts:
            - name: xnat-conf
              mountPath: /xnat
        - name: node-conf
          image: {{ include "xnat.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              set -x
              echo "node.id=$HOSTNAME" > /xnat/node-conf.properties
          volumeMounts:
            - name: node-conf
              mountPath: /xnat
        {{- if .Values.auth.openid.enabled }}
        - name: openid-conf
          image: {{ include "xnat.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: OPENID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.openid.secretName }}
                  key: clientId
            - name: OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.openid.secretName }}
                  key: clientSecret
          command:
            - /bin/bash
            - -c
            - |
              set -x
              cat <<EOF > /xnat/{{- .Values.auth.openid.provider -}}-provider.properties
              name="UCL SSO"
              provider.id={{- .Values.auth.openid.provider }}
              auth.method=openid
              auto.enabled=false
              auto.verified=false
              siteUrl={{ .Values.siteUrl }}
              openid.{{- .Values.auth.openid.provider -}}.clientId=$(OPENID_CLIENT_ID)
              openid.{{- .Values.auth.openid.provider -}}.clientSecret=$(OPENID_CLIENT_SECRET)
              openid.{{- .Values.auth.openid.provider -}}.accessTokenUri={{ .Values.auth.openid.accessTokenUri }}
              openid.{{- .Values.auth.openid.provider -}}.userAuthUri={{ .Values.auth.openid.userAuthUri }}
              openid.{{- .Values.auth.openid.provider -}}.link=<a href="/openid-login?providerId={{- .Values.auth.openid.provider -}}">{{ .Values.auth.openid.link }}</a>
              openid.{{- .Values.auth.openid.provider -}}.forceUserCreate=true
              openid.{{- .Values.auth.openid.provider -}}.emailProperty=email
              openid.{{- .Values.auth.openid.provider -}}.givenNameProperty=name
              openid.{{- .Values.auth.openid.provider -}}.familyNameProperty=deliberately_unknown_property
              EOF
          volumeMounts:
            - name: openid-conf
              mountPath: /xnat
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.logging.enabled }}
        - name: alloy-config
          configMap:
            name: {{ include "xnat.fullname" . }}-alloy-config
            items:
              - key: config.alloy
                path: config.alloy
        {{- end }}
        - name: node-conf
        - name: xnat-conf
      {{- if .Values.auth.openid.enabled }}
        - name: openid-conf
      {{- end }}
      {{- range $vol := (concat .Values.volumes .Values.extraVolumes) }}
        - name: {{ $vol.name }}
        {{- if and $vol.persistent $vol.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ printf "%s-%s" (include "xnat.fullname" $) $vol.name }}
        {{- else if not $vol.persistent }}
          {{- if or .configMap .secret }}
          {{- range $key, $value := $vol }}
            {{- if not (eq $key "name") }}
          {{ $key }}:
          {{- toYaml $value | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        {{- end }}
      {{- end }}
  volumeClaimTemplates:
  {{- range $vol := (concat .Values.volumes .Values.extraVolumes) }}
  {{- if and $vol.persistent (not $vol.existingClaim) }}
    - metadata:
        name: {{ $vol.name }}
      {{- with $vol.annotations }}
        annotations:
        {{- range $key, $value := . }}
          {{ $key }}: {{ $value }}
        {{- end }}
      {{- end }}
      spec:
        accessModes: [ {{ $vol.accessMode | quote }} ]
        resources:
          requests:
            storage: {{ $vol.size | quote }}
      {{- if $vol.storageClass }}
        {{- if (eq "-" $vol.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ $vol.storageClass }}"
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}