---
replicaCount: 2

fullnameOverride: xnat-core

image:
  name: xnat-core
  tag: latest

imageCredentials:
  enabled: true
  registry: ghcr.io

postgresql:
  fullnameOverride: xnat-core-postgresql
  cluster:
    initdb:
      database: xnatdb
      owner: xnatuser

web:
  siteUrl: http://localhost
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
      nginx.ingress.kubernetes.io/client-body-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "32k"
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/affinity-mode: "persistent"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "1800"
      nginx.ingress.kubernetes.io/session-cookie-expires: "1800"
      nginx.ingress.kubernetes.io/session-cookie-name: "xnat-core-dev"
    hosts:
      - host: localhost
  config:
    extraWait: 15
