apiVersion: v1
stringData:
  username: xnatuser
  password: xnatpass
  dbname: xnatdb
kind: Secret
metadata:
  name: pg-user-secret
  namespace: xnat-core
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  username: xnatuser
  password: xnatpass
  dbname: xnatdb
kind: Secret
metadata:
  name: xnat-core-db-app
  namespace: xnat-core
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  adminPassword: strongPassword
  serviceAdminPassword: anotherStrongPassword
kind: Secret
metadata:
  name: localdb-secret
  namespace: xnat-core
type: kubernetes.io/opaque
