---
name: Helm Chart Testing

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  cancel-in-progress: true
  group: >-
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  helm-chart-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: 3.x

      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          config: chart/ci/kind-config.yaml
          cluster_name: xnat
          wait: 120s

      - name: Install kubectl
        uses: azure/setup-kubectl@0c5e050edfed71b2b50731ab044d42489d51c129 # v4.0.0

      - name: Set up Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: v3.17.0

      - name: Install CNPG operator and wait for pods to be ready
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts
          helm repo update
          helm upgrade --install cnpg \
            --namespace cnpg-system \
            --create-namespace \
            cnpg/cloudnative-pg
          kubectl wait --for=condition=Ready pod \
            --all \
            --namespace cnpg-system \
            --timeout=300s

      - name: Install NGINX Ingress Controller and wait for pods to be ready
        run: |
          helm repo add nginx https://kubernetes.github.io/ingress-nginx/
          helm repo update
          helm upgrade --install nginx \
              --namespace nginx-ingress \
              --create-namespace \
              nginx/ingress-nginx
          kubectl wait --for=condition=Ready pod \
            --all \
            --namespace nginx-ingress \
            --timeout=300s

      - name: Create required resources
        run: |
          kubectl apply -f chart/ci/manifests/namespace.yaml
          kubectl apply -f chart/ci/manifests/secrets.yaml

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Run chart-testing (install)
        run: >-
          ct install --config ct.yaml --helm-extra-set-args="
            --set imageCredentials.username=${{ secrets.GHCR_USER }}
            --set imageCredentials.password=${{ secrets.GHCR_PAT }}
            "
