---
name: Publish chart

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.2.0
        with:
          version: v3.17.0

      - name: Add Helm repos for dependencies
        run: |
          helm repo add cnpg https://cloudnative-pg.github.io/charts

      - name: Lowercase repository owner
        run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"

      - name: Login
        run: >-
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{
          env.REGISTRY }}/${{ env.REPO_OWNER }} --username ${{ github.actor }}
          --password-stdin

      - name: Package and push
        working-directory: ./chart
        run: |
          helm dependency build
          helm package .
          helm push ./*.tgz oci://${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/charts

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1
        with:
          charts_dir: .
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_RELEASE_NAME_TEMPLATE: "{{ .Version }}"
