---
name: Publish chart

on:
  push:
    tags:
      - "*"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          ref: drmatthews/gh-pages

      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.17.0

      - name: Lowercase repository owner
        run: echo "REPO_OWNER=${GITHUB_REPOSITORY_OWNER@L}" >> "${GITHUB_ENV}"

      - name: Login
        run: >-
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{
          env.REGISTRY }}/${{ env.REPO_OWNER }} --username ${{ github.actor }}
          --password-stdin

      - name: Package and push
        working-directory: ./chart
        run: |
          helm dependency build
          helm package .
          helm push ./*.tgz oci://${{ env.REGISTRY }}/${{ env.REPO_OWNER }}/charts

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          charts_dir: ./chart
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
